### ISSUE TITLE
'Select a Place' Screen

### ISSUE THREAD

**Issue by kyukyukyu** [incremental-binary/launduler-app#2]
# UI Mockup

https://app.moqups.com/sanggyu.nam/VYGop9ADyN/view/page/aea588b24

# TODO

- [x] Add the layout
- [x] Retrieve the place list
- [x] Implement a base activity for this screen
- [x] Implement an activity for this screen jumped from 'Explore' screen
- [x] Implement an activity for this screen at the first place of the reservation

# Considerations

* Layout and activity reuse: we reuse this layout for selecting a place in the reservation process.
