### ISSUE TITLE
'Explore' page

### ISSUE THREAD

**Issue by Thrii** [incremental-binary/launduler-app#3]
# UI Mockup
https://app.moqups.com/sanggyu.nam/VYGop9ADyN/view/page/a48f312cf
# Todo
- [x] 서버로부터 machine 목록 받아오기
- [x] 화면에 machine 목록 및 정보 출력
- [x] Machine item 탭 했을 때의 액션 구현
