### ISSUE TITLE
Status of a Machine 화면 구현

### ISSUE THREAD

**Issue by kyukyukyu** [incremental-binary/launduler-app#4]
# UI Mockups

* Explore 화면에서 세탁기를 골랐을 때: https://app.moqups.com/sanggyu.nam/VYGop9ADyN/view/page/acc232862
* 예약 변경 과정에서 세탁기를 골랐을 때: https://app.moqups.com/sanggyu.nam/VYGop9ADyN/view/page/aa741f698

# 고려사항

* Activity 재활용: 이 화면을 위한 base activity를 정의하고 이를 상속하여 각 경우를 위한 activity를 정의할 것.
* Navigation drawer UI 패턴: 이슈 #5 참조. 화면의 toolbar 아래의, 내용에 대응하는 부분을 fragment로 구현할 것.
* Datepicker: ~~[wdullaer/MaterialDateTimePicker](https://github.com/wdullaer/MaterialDateTimePicker)~~ [infinum/MaterialDateTimePicker](https://github.com/infinum/MaterialDateTimePicker) 사용.
* RxAndroid: 서로 다른 view 사이에서 데이터를 교환할 때 RxAndroid에서 제공하는 [Observable](http://reactivex.io/documentation/observable.html)을 사용할 것.

# TODO

* [x] 날짜 선택 fragment layout 추가
* [x] 예약 현황 표시 fragment layout 추가
* [x] Base activity 구현
    * [x] Toolbar 설정
    * [x] 예약 현황 서버에서 가져오기
    * [x] 예약 현황 표시
    * [x] 예약 생성/변경
        * [x] Floating action button 아이콘 적용
        * [x] Floating action button click listener 구현
        * [x] Datepicker 표시 구현
* [ ] Explore 화면에서 세탁기를 골랐을 때 activity 구현
    * [ ] 고장 신고
        * [x] Toolbar에 고장 신고 메뉴 추가
        * [ ] 고장 신고 dialog 및 완료시 snackbar 표시 구현
        * [ ] 서버에 고장 신고 요청 보내기
    * [ ] 예약 생성
        * [ ] 완료시 snackbar 표시 구현
        * [ ] 서버에 예약 생성 요청 보내기
* [ ] 예약 변경 과정에서 세탁기를 골랐을 때 activity 구현
    * [ ] 예약 변경
        * [ ] 완료시 snackbar 표시 구현
        * [ ] 서버에 예약 변경 요청 보내기

**Comment by kyukyukyu** [comment]
원래 사용하기로 했던 datepicker 라이브러리가 Android Support Library를 지원하지 않는다. 이를 지원하는 원래 datepicker 라이브러리의 [fork가 존재](https://github.com/infinum/MaterialDateTimePicker)하므로 이것을 사용하도록 한다.

**Comment by kyukyukyu** [comment]
두 경우에 대해 각각 다른 activity를 정의하고, 각 activity에서 (support library에서 제공하는) toolbar view를 action bar로 등록하고, options menu item을 정의하는 로직을 fragment 클래스 안에서 구현하도록 하면 될 듯. Options menu의 resource ID를 제공하는 함수가 선언된 interface를 새로 정의해서 fragment들이 구현하도록 하고, activity에서는 이 인터페이스의 구현에 맞춰서 toolbar의 menu items를 업데이트하면 될 듯.
