### ISSUE TITLE
Reservation Page

### ISSUE THREAD

**Issue by Thrii** [incremental-binary/launduler-app#6]
# UI Mockup
https://app.moqups.com/sanggyu.nam/VYGop9ADyN/view/page/a6e7404c0
# Issues
* 예약 있을 때와 없을 때 화면 구분하기
* 다른 activity 호출할 때 데이터 전달 : 데이터 이름 및 역할 정의 후, 다른 activity에서 이를 get할 수 있도록 수정

# Todo
- [ ] 예약 있을 때의 화면
  - [ ] Calender에 예약 표시
  - [ ] 예약 취소 기능 구현
  - [ ] 예약 변경 기능 구현
    - [ ] Select a Place screen으로 이동
- [ ] 예약 없을 때의 화면
  - [ ] ExploreActivity로 이동하여 예약 시작 구현
