### ISSUE TITLE
Alternative Services 화면 구현

### ISSUE THREAD

**Issue by kyukyukyu** [incremental-binary/launduler-app#7]
# UI Mockup

https://app.moqups.com/sanggyu.nam/VYGop9ADyN/view/page/a798c73e6

# 고려사항

* [RecyclerView](https://developer.android.com/training/material/lists-cards.html) 사용

# TODO

* [ ] Fragment 레이아웃 생성
* [ ] 리스트 항목 레이아웃 생성
* [ ] API 사용하여 리스트 받아오기 구현
* [ ] 클릭 이벤트 리스너 구현
